/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.iths;

import java.sql.SQLException;
import java.util.Collection;

public class App {
    public static void main(String[] args) throws SQLException {
      App app = new App();
      try {
          app.load();
      } catch (SQLException e) {
          System.err.printf("Något gick fel vid inläsning av databas! (%s)%n", e);
      }
    }

    private void load() throws SQLException {
        
    }
}
