/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.iths;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;

public class App {

    public final static String JDBC_Connection = "jdbc:mysql://localhost:3306/iths";
    public final static String JDBC_User = "iths";
    public final static String JDBC_PASSWORD = "iths";
    public final static String SQL_SELECT_ALL_STUDENTS = "SELECT StudentId, FirstName, LastName FROM Student";
    public final static String SQL_COL_STUDENT_ID = "StudentId";
    public final static String SQL_COL_STUDENT_FIRSTNAME = "FirstName";
    public final static String SQL_COL_STUDENT_LASTNAME = "LastName";
    public final static String SQL_SELECT_SCHOOL_FOR_STUDENTS = "SELECT SchoolId, Name, City,FirstName, LastName FROM StudentSchool JOIN Student USING (StudentId) JOIN School USING (SchoolId) WHERE StudentId = ?";
    public final static String SQL_COL_SCHOOL_NAME = "Name";
    public final static String SQL_COL_SCHOOL_ID = "SchoolId";
    public final static String SQL_COL_SCHOOL_CITY = "City";
    public static void main(String[] args) throws SQLException {
      App app = new App();
      try {
          app.load();
      } catch (SQLException e) {
          System.err.printf("Något gick fel vid inläsning av databas! (%s)%n", e);
      }
    }

    private void load() throws SQLException {
        Collection<Student> students = loadStudents();
        for (Student student : students){
            System.out.println(student);
        }
    }

    private Collection<Student> loadStudents() throws SQLException {
        Collection<Student> students = new ArrayList<>();
        Connection con = DriverManager.getConnection(JDBC_Connection, JDBC_User, JDBC_PASSWORD);
        ResultSet rs = con.createStatement().executeQuery(SQL_SELECT_ALL_STUDENTS);
        while (rs.next()){
            int studentId = (int) rs.getLong(SQL_COL_STUDENT_ID);
            String lastName = rs.getString(SQL_COL_STUDENT_LASTNAME);
            String firstName = rs.getString(SQL_COL_STUDENT_FIRSTNAME);
            Student student = new Student(studentId, firstName,lastName);
            students.add(student);
            Collection<School> schools = loadSchools(student.getStudentId());
            for (School school : schools) {
                student.add(school);
            }
        }
    }

}
